### ISSUE TITLE
Create a dmg to tell users to copy the app to their Application folder

### ISSUE THREAD

**Issue by bumi** [getAlby/alby-installer-macos#1]
The `Alby.app` must be put in a place where it stays and is not moved. So the downloads folder is not good enough for that. 
We must tell people to put the app in their Applications folder. 

I think most macOS apps have some nice looking dmg that allows people to drag & drop the app to the Applications folder. 
we should also package the app like that.

**Comment by stuffmc** [comment]
Alternatively, and better imho, is to have the App move itself at start-up to `/Applications`. This require probably the same amount of work as to create a DMG, but the later doesn't imply people will move it to `/Applications`. They could move it to `~/Download` or even `~/tmp` ;).

Creating an installer is not something many app do on macOS.

**Comment by bumi** [comment]
ah. ok, that is possible and a good practice? So then a user can download the app (e.g. also from the Mac App Store?) and once the app is opened the app makes sure it is in the Applications folder?

**Comment by stuffmc** [comment]
Oh boy. From the App Store ;-) If you ever want the App to be on the App Store it probably means it has to be Sandboxed (not sure anymore, would need to check) and then if so, it means we can't copy the `.json` unless the user selects the target folder. You really don't need to be on the App Store, unless you want your extension to be discovered this way. We could then do 2 versions of the app — but that means making a separate ticket since this is another discussion.

**Comment by bumi** [comment]
ok, thanks for the explanation! we ignore the app store for now :)
